name = "thalisky/unicodeprogressbar"
version = "0.2.5"
description = "Generates a unicode progress-bar"
authors = ["thalisky"]
repository = "https://github.com/thalisky/unicodeprogressbar"
license = "CC BY-SA 4.0"
includes = [
	"pesde.toml",
	"README.md",
	"LICENSE",
	"unicodeprogressbar/**",
]

[target]
environment = "roblox"
lib = "unicodeprogressbar/init.lua"
build_files = ["unicodeprogressbar"]

[indices]
default = "https://github.com/pesde-pkg/index"

[scripts]
roblox_sync_config_generator = ".pesde/scripts/roblox_sync_config_generator.luau"
sourcemap_generator = ".pesde/scripts/sourcemap_generator.luau"

[dev_dependencies]
scripts = { name = "pesde/scripts_rojo", version = "^0.2.0", target = "lune" }
rojo = { name = "pesde/rojo", version = "^7.5.1", target = "lune" }

[engines]
pesde = "^0.7.0"
lune = "^0.10.2"
