[package]
name = "khanmenthe/unicodeprogressbar"
description = "Generates a unicode progress-bar"
license = "CC BY-SA 4.0"
repository = "https://github.com/thalisky/unicodeprogressbar"
version = "0.2.2"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"
exclude = ["**"]
include = [
    "default.project.json",
    "src",
    "src/**",
    "LICENSE",
    "wally.toml",
]

[dependencies]
